#!/bin/bash
# fog-required-ordinals.sh — regenerate packages/d2fog/required-ordinals.txt from the engine trees.
#
# Our Fog.dll replaces Blizzard's, so every ordinal any engine IMPORTS has to be one we export. Get
# that wrong and wine aborts the process the first time the engine calls it — which does not look
# like a missing export, it looks like the server going silent at 0% CPU. Fog @10265 cost a day
# that way: 1.10f's Fog ends at ordinal 10264 and 1.13c added three more.
#
# The engines' own import tables are the authority, so they are read straight out of the real DLLs
# and written down. The result is committed and asserted by a unit test, which is what makes the
# check run on a machine that has no game files at all.
#
#   tools/fog-required-ordinals.sh          rewrite the manifest from $TREES
#   TREES=/path tools/fog-required-ordinals.sh
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(pwd)"
[ -f "$ROOT/.env" ] && set -a && . "$ROOT/.env" && set +a
TREES="${TREES:-$ROOT/.stack}"
OUT="$ROOT/packages/d2fog/required-ordinals.txt"

python3 - "$TREES" "$OUT" <<'PYEOF'
import struct, sys, os, collections

trees, out = sys.argv[1], sys.argv[2]

def fog_imports(path):
    """Every Fog.dll ordinal this PE imports by number."""
    d = open(path, 'rb').read()
    pe = struct.unpack_from('<I', d, 0x3c)[0]
    if d[pe:pe+4] != b'PE\0\0':
        return set()
    nsec = struct.unpack_from('<H', d, pe+6)[0]
    optsz = struct.unpack_from('<H', d, pe+20)[0]
    imp = struct.unpack_from('<I', d, pe+24+96+8)[0]
    secs, off = [], pe+24+optsz
    for _ in range(nsec):
        vs, va, rs, pr = struct.unpack_from('<IIII', d, off+8)
        secs.append((va, vs, pr, rs)); off += 40
    def r2f(r):
        for va, vs, pr, rs in secs:
            if va <= r < va + max(vs, rs):
                return pr + (r - va)
    o = r2f(imp)
    found = set()
    while o is not None and o + 20 <= len(d):
        olt, ts, fc, name, iat = struct.unpack_from('<IIIII', d, o)
        if name == 0:
            break
        nf = r2f(name)
        dll = d[nf:].split(b'\0')[0].decode('latin1').lower() if nf is not None else ''
        t = r2f(olt or iat); k = 0
        while t is not None and t + k*4 + 4 <= len(d):
            v = struct.unpack_from('<I', d, t + k*4)[0]
            if v == 0:
                break
            if dll == 'fog.dll' and v & 0x80000000:
                found.add(v & 0xffff)
            k += 1
        o += 20
    return found

# gs110f -> 1.10f. The tag is the tree name with the dots taken out, so put them back the one way
# that round-trips: a single digit, a dot, then the rest.
def version_of(tree):
    t = tree[2:]
    return t[0] + '.' + t[1:]

rows = collections.defaultdict(dict)   # version -> dll -> set(ordinals)
for entry in sorted(os.listdir(trees)):
    # Only the canonical per-engine trees. Scratch variants like `gs109d-era` are somebody's
    # experiment, and a manifest that quietly includes one is a manifest nobody can regenerate.
    if not entry.startswith('gs') or '-' in entry or not os.path.isdir(os.path.join(trees, entry)):
        continue
    ver = version_of(entry)
    for f in sorted(os.listdir(os.path.join(trees, entry))):
        if not f.lower().endswith('.dll') or f.lower() == 'fog.dll':
            continue
        try:
            s = fog_imports(os.path.join(trees, entry, f))
        except Exception:
            continue
        if s:
            rows[ver][f] = s

with open(out, 'w') as fh:
    fh.write("""# Fog ordinals each engine imports. GENERATED by tools/fog-required-ordinals.sh — do not hand-edit.
#
# Our Fog.dll replaces Blizzard's, so an ordinal an engine imports and we do not export is a wine
# ABORT the first time it is called. That presents as the server going quiet at 0% CPU, not as a
# missing export, which is why this is checked mechanically instead of noticed.
#
# One row per <version> <importing-dll> <ordinal...>. `packages/d2fog/ordinals.zig` asserts that
# fog.def covers every row it is required to; the rule about which rows those are, and why D2CMP
# is not one of them, is written down there rather than here.
""")
    for ver in sorted(rows):
        for dll in sorted(rows[ver]):
            fh.write('%-6s %-14s %s\n' % (ver, dll, ' '.join(str(o) for o in sorted(rows[ver][dll]))))
print('wrote %s (%d versions)' % (out, len(rows)))
PYEOF
